django-app/app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user_account.urls', namespace='user_account')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

django-app/app/user_account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user_account.views import (
    UserAccountCreateView,
    UserAccountLoginView,
    UserAccountDetailView,
    UserAccountChangePasswordView
)

app_name = 'user_account'

urlpatterns = [
    path('signup/<str:referral_code>/', UserAccountCreateView.as_view(),
         name='create_with_referral'),
    path('signup/', UserAccountCreateView.as_view(), name='create'),

    path('login/', UserAccountLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]


# For profile routes
urlpatterns += [
    path('profile/', UserAccountDetailView.as_view(), name='detail_home'),
]

# For password

urlpatterns += [
    path('password/change/', UserAccountChangePasswordView.as_view(),
         name='change_password'),
]

django-app/app/templates/navbars/app_base_navbar_left.html
{% load static %}

{% block navbar-left %}
<div class="app__navbar-left" id="app__navbar-left">
	<ul class="app__navbar-left-ul">
		<li class="app__navbar-left-item">

			<a class="app__navbar-left-link" href="">
				<span class="app__left-nav-button-icon material-icons material-icons-outlined">
					home
				</span>
				Home
			</a>
		</li>
		<li class="app__navbar-left-dropdown">
		<li class="app__navbar-left-item">
			<a class="app__navbar-left-link" onclick="navbarLeftDropdownToggle('app__navbar-left-ul-1')">
				<span class="app__left-nav-button-icon material-icons material-icons-outlined">
					apps
				</span>
				ML Studio
				<span class="app__left-nav-button-icon material-icons material-icons-outlined">
					expand_more
				</span>
			</a>
		</li>
		<ul class="app__navbar-left-ul app__navbar-left-ul-1">
			<li class="app__navbar-left-item">
				<a class="app__navbar-left-link" href="">Custom Model</a>
			</li>
			<li class="app__navbar-left-item">
				<a class="app__navbar-left-link" href="">Predict</a>
			</li>
		</ul>
		</li>

	</ul>
	<hr style="width: 80%;">
	<ul class="app__navbar-left-ul">

		<li class="app__navbar-left-item">

			<a class="app__navbar-left-link" href="">
				<span class="app__left-nav-button-icon material-icons material-icons-outlined">
					home
				</span>
				Home
			</a>
		</li>

	</ul>
</div>
{% endblock navbar-left %}

django-app/app/templates/navbars/navbar_top.html
{% load static %}
{% block navbar %}

<nav class="navbar navbar-expand fixed-top navbar-light bg-light shadow-sm rounded app__top-nav" id="navbar">
	<a class="app__top-nav-button" onclick="navbarLeftToggle()">
		<span class="app__top-nav-button-icon app__top-nav-trigger material-icons material-icons-outlined">
			view_headline
		</span>
	</a>
	<a class="navbar-brand app__top-nav-brand">{{request.site.name}}</a>
	<div class="collapse navbar-expand navbar-collapse" id="navbarNavDropdown">
		<div class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
				<li class="nav-item dropdown">
					<a class="nav-link app__top-nav-hov dropdown-toggle"
					id="navbarDropdown"
					role="button"
					data-toggle="dropdown"
					aria-haspopup="true"
					aria-expanded="false">
						<span class="app__top-nav-profile-icon material-icons material-icons-outlined">
							account_circle
						</span>
					</a>
				<div class="dropdown-menu dropdown-menu-right"
					 aria-labelledby="navbarDropdown">
					<a class="dropdown-item">Page 1</a>
					<a class="dropdown-item" href="{% url 'user_account:detail_home' %}">
						<i class="fas fa-cog profile-icon"></i>Profile
					</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'user_account:logout' %}">Logout</a>
				</div>
			</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link app__top-nav-hov {% if request.path == '/account/signup/' %} app__top-nav-active{% endif %}" 
						id="app__top-nav-signup-btn"
						href="{% url 'user_account:create' %}"
						type="button"
						name="button">Sign Up</a>
				</li>
				<li class="nav-item">
					<a class="nav-link app__top-nav-hov {% if request.path == '/account/login/' %} app__top-nav-active{% endif %}" 
						id="app__top-nav-signin-btn"
						href="{% url 'user_account:login' %}"
						type="button"
						name="button">Login</a>
				</li>
			{% endif %}
		</div>
	</div>
</nav>

{% endblock navbar %}